version: "3"
services:
  mongo-intravel:
    image: mongo:5.0.6
    container_name: mongo_data
    hostname: mongo_data
    networks:
      - intravel-net

  cost-allocation:
    image: intravel_image
    container_name: intravel_app
    expose:
      - 21350
    labels:
      - traefik.enable=true
      - traefik.http.routers.cost-allocation.rule=PathPrefix(`/intravel`)
    networks:
      - intravel-net

networks:
  intravel-net:
